const path = require('path');
const {
  withProjectBuildGradle,
  withEntitlementsPlist,
  withInfoPlist,
  withAndroidManifest,
  withPlugins,
  AndroidConfig,
} = require('@expo/config-plugins');

// Adds a Gradle `flatDir` repository pointing at rarime-rn-sdk's prebuilt AARs (noir.aar etc.),
// which ship inside the package rather than being published to a Maven repo.
//
// FIXED 2026-07-26: this used to hardcode `new File(rootDir, '../../android/libs')` - a leftover
// from the old layout where rarime-rn-sdk was an autolinked SIBLING module two directories up. It
// is now a GitHub npm dependency ("@rarimo/rarime-rn-sdk": "github:quidmints/rarime-rn-sdk#main"),
// so the AARs live under node_modules and that path resolves to nothing; Gradle would simply fail
// to find the AAR at device-build time.
//
// Rather than swap one hardcoded relative path for another, resolve where the package actually is:
// this plugin is plain Node, so it can ask the module resolver, which stays correct under
// hoisting, monorepo layouts and pnpm-style stores alike.
//
// NOT VERIFIED BY A REAL ANDROID BUILD - no JDK/Android SDK/NDK on the machine this was written on
// (TODO.md sec. 1). The resolution is checked at config time and warns loudly if the package is
// missing, but the resulting Gradle file has never been fed to Gradle. Confirm on a machine or CI
// runner that has the Android toolchain.
function resolveSdkLibsDir() {
  try {
    const pkgJson = require.resolve('@rarimo/rarime-rn-sdk/package.json', { paths: [__dirname] });
    return path.join(path.dirname(pkgJson), 'android', 'libs');
  } catch {
    return null;
  }
}

function addFlatDirToRootBuildGradle(buildGradle, libsDir) {
  // Groovy string literal - escape backslashes so Windows paths survive. An absolute resolved path
  // is used rather than one relative to `rootDir`, since node_modules may be hoisted anywhere above
  // the android/ directory.
  const groovyPath = libsDir.replace(/\\/g, '\\\\');
  const marker = `dirs '${groovyPath}'`;

  if (buildGradle.includes(marker)) return buildGradle;

  const flatDirCode = `
  flatDir {
    // rarime-rn-sdk ships prebuilt AARs (noir.aar) in the npm package; path resolved by app.plugin.js
    ${marker}
  }
  `;

  const pattern = /allprojects\s*\{[\s\S]*?repositories\s*\{/;
  if (!buildGradle.match(pattern)) {
    console.warn('WARNING: Could not find "allprojects { repositories {" in android/build.gradle');
    return buildGradle;
  }

  return buildGradle.replace(pattern, (match) => `${match}\n${flatDirCode}`);
}

const withAndroidFlatDir = (config) => {
  const libsDir = resolveSdkLibsDir();
  if (!libsDir) {
    console.warn(
      'WARNING: could not resolve @rarimo/rarime-rn-sdk - skipping the flatDir repository. ' +
        'The Android build will not find noir.aar. Run an install first.'
    );
    return config;
  }

  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language === 'groovy') {
      cfg.modResults.contents = addFlatDirToRootBuildGradle(cfg.modResults.contents, libsDir);
    }
    return cfg;
  });
};

// ---------------------------------------------------------------------------------------------
//  NFC: the permission to read a passport chip (sec. 2.18ap).
//
//  WHAT THIS DOES AND, MORE IMPORTANTLY, WHAT IT DOES NOT. This declares the capability. It does NOT
//  add a scanner: there is no NFC library in this app's dependencies and no scan code in src/, and
//  the SDK does not provide one either - `@rarimo/rarime-rn-sdk` is a PROVING sdk (its native
//  payload is SwoirenbergLib, a Noir prover) with zero NFC references anywhere in its source.
//  App.tsx says as much already: live add/renew/revoke need "a scanned passport (RarimePassport from
//  NFC)". So this removes one of two blockers, and the other is a real piece of work.
//
//  IT IS STILL WORTH DOING FIRST, because it is the blocker that fails LATEST and most confusingly.
//  On iOS the entitlement is enforced at RUNTIME: a build without it compiles, installs, launches,
//  and then throws when a reader session starts. Landing it now means the first session with a real
//  passport is spent on the scanner, not on discovering a provisioning problem.
//
//  WHY A CONFIG PLUGIN RATHER THAN EDITING ios/ AND android/. Neither directory exists in the repo -
//  they are generated by `expo prebuild`, and `--clean` (which package.json's prebuild script
//  passes) deletes and regenerates them. Hand edits would vanish on the next prebuild.
// ---------------------------------------------------------------------------------------------

/// The ICAO 9303 LDS1 eMRTD application identifier. iOS requires every AID an app may SELECT to be
/// declared up front; a chip whose AID is not listed cannot be talked to at all.
const EMRTD_AID = 'A0000002471001';

const NFC_USAGE_DESCRIPTION =
  'Hold your passport or ID card against the top of your phone to read its chip. The document data ' +
  'stays on this device.';

// Pure transforms, kept separate from the plugin wrappers so they can be asserted directly - the
// plugin is plain Node, so this is testable here without an Xcode or Android toolchain
// (app.plugin.test.js). The Gradle change above has no such test and its own comment says it has
// never been fed to Gradle.

function addNfcEntitlements(entitlements) {
  const formats = new Set(entitlements['com.apple.developer.nfc.readersession.formats'] || []);
  // 'TAG' is raw ISO7816 tag access, which is what reading an eMRTD needs. 'NDEF' is the other
  // format and is NOT sufficient - a passport chip is not an NDEF tag.
  formats.add('TAG');
  return {
    ...entitlements,
    'com.apple.developer.nfc.readersession.formats': [...formats],
  };
}

function addNfcInfoPlist(infoPlist) {
  // Confusingly named: `select-identifiers` looks like an entitlement but Apple reads it from
  // Info.plist. Getting this wrong produces a runtime failure with no build-time warning.
  const aids = new Set(
    infoPlist['com.apple.developer.nfc.readersession.iso7816.select-identifiers'] || []
  );
  aids.add(EMRTD_AID);
  return {
    ...infoPlist,
    NFCReaderUsageDescription: infoPlist.NFCReaderUsageDescription || NFC_USAGE_DESCRIPTION,
    'com.apple.developer.nfc.readersession.iso7816.select-identifiers': [...aids],
  };
}

/// `required: false` on purpose. Marking the NFC feature required would stop the app installing on
/// devices without an NFC radio - and a user who restored from backup (identity/recovery.ts) can
/// still hold notes and withdraw without ever reading a document. Excluding those devices would buy
/// nothing and cost users.
function addNfcFeature(androidManifest) {
  const manifest = androidManifest.manifest;
  const features = manifest['uses-feature'] || [];
  const already = features.some(
    (f) => f && f.$ && f.$['android:name'] === 'android.hardware.nfc'
  );
  if (!already) {
    features.push({
      $: { 'android:name': 'android.hardware.nfc', 'android:required': 'false' },
    });
  }
  manifest['uses-feature'] = features;
  return androidManifest;
}

const withNfc = (config) =>
  withPlugins(config, [
    (cfg) => withEntitlementsPlist(cfg, (c) => {
      c.modResults = addNfcEntitlements(c.modResults);
      return c;
    }),
    (cfg) => withInfoPlist(cfg, (c) => {
      c.modResults = addNfcInfoPlist(c.modResults);
      return c;
    }),
    (cfg) => AndroidConfig.Permissions.withPermissions(cfg, ['android.permission.NFC']),
    (cfg) => withAndroidManifest(cfg, (c) => {
      c.modResults = addNfcFeature(c.modResults);
      return c;
    }),
  ]);

const withQuidWallet = (config) => withNfc(withAndroidFlatDir(config));

module.exports = withQuidWallet;
// Exported for app.plugin.test.js - the transforms are pure, so they can be checked without a build.
module.exports.addNfcEntitlements = addNfcEntitlements;
module.exports.addNfcInfoPlist = addNfcInfoPlist;
module.exports.addNfcFeature = addNfcFeature;
module.exports.EMRTD_AID = EMRTD_AID;
