// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

import {Test} from 'forge-std/Test.sol';
import {NotaryActionHonkVerifier} from '../../contracts/title/NotaryActionHonkVerifier.sol';
import {INoirVerifier} from '../../contracts/interfaces/verifiers/INoirVerifier.sol';

/*
 * THE GENERATED VERIFIER FOR ANONYMOUS NOTARY AUTHORISATION (sec. 2.18am).
 *
 * WHY THIS FILE EXISTS AT ALL. sec. 2.18ad item 4 states the rule: a verifier that has never
 * accepted a proof is a liability, because a later failure cannot be attributed - is it your change,
 * or the never-exercised path underneath it? Every other circuit that needed a real document had to
 * wait. THIS ONE DOES NOT: `notary_action`'s witness is a field element and a Merkle path, so a
 * genuine proof can be produced here and now. There was no reason to ship it unexercised.
 *
 * FIXTURE PROVENANCE. `backend/circuits/notary_action/Prover.toml`, regenerated by
 * `backend/circuits/codegen-verifiers.sh` (needs `bb` on PATH - it lives at ~/.bb-v12/bb here).
 * sk_identity 8675309 with an all-zero sibling path: a single-leaf notary tree whose root IS the
 * leaf hash Poseidon(secret_commitment(derive_notary_secret(sk)), STATUS_CLEAN, 1) - the secret is
 * DERIVED from the identity key (sec. 2.18au), never held separately. That root was PRINTED BY THE
 * CIRCUIT'S OWN PRIMITIVES rather than hand-computed, so it cannot drift from what
 * `smt_verifier_full` expects.
 *
 * NOTE THE PROOF BYTES CHANGE ON EVERY REGENERATION and that is correct: bb 1.x produces
 * zero-knowledge proofs by default, so the blinding differs run to run. A fixture that reproduced
 * byte-for-byte would be evidence the witness was NOT being hidden.
 */
contract NotaryActionHonkVerifierTest is Test {
  INoirVerifier internal verifier;

  /// Poseidon(secret_commitment(derive_notary_secret(8675309)), STATUS_CLEAN, 1) - see Prover.toml.
  uint256 internal constant NOTARY_ROOT =
    0x0d7c34b0a42ad19f29be9642f33feb5d8a7a0255895cab5519d5bda33d9dfd54;
  uint256 internal constant ACTION_CONTEXT = 424242;

  function setUp() public {
    verifier = INoirVerifier(address(new NotaryActionHonkVerifier()));
  }

  function _proof() internal view returns (bytes memory) {
    return vm.readFileBinary('test/fixtures/notary_action.proof');
  }

  function _publicInputs() internal pure returns (bytes32[] memory _inputs) {
    _inputs = new bytes32[](2);
    _inputs[0] = bytes32(NOTARY_ROOT);
    _inputs[1] = bytes32(ACTION_CONTEXT);
  }

  /// The baseline: an active notary's proof verifies on-chain.
  function test_VerifiesRealProof() public view {
    assertTrue(verifier.verify(_proof(), _publicInputs()), 'a genuine notary proof was rejected');
  }

  /*
   * THE SUBSTITUTION PROPERTY, which is what binds a proof to ONE action (sec. 2.18ah).
   *
   * `action_context` is declared `pub` but the circuit body never reads it - nargo warns about
   * exactly that, and `let _ = action_context;` says the omission is deliberate. The binding works
   * because `TitleLedger` will hand the verifier the context IT derives from the action, not the one
   * in the proof. That substitution proves nothing unless the value is genuinely bound into the
   * transcript, so this asserts it: a proof made for one action must fail against another.
   *
   * Without this test the whole anti-replay argument would rest on a compiler warning being benign.
   */
  function test_RejectsAnActionContextItWasNotMadeFor() public view {
    bytes32[] memory _inputs = _publicInputs();
    _inputs[1] = bytes32(ACTION_CONTEXT + 1);
    _assertRejects(_inputs);
  }

  /// A proof is equally bound to the ROOT it was made against, so a stale or foreign notary
  /// snapshot cannot be substituted - the separation task #12's per-jurisdiction roots rely on.
  function test_RejectsADifferentNotaryRoot() public view {
    bytes32[] memory _inputs = _publicInputs();
    _inputs[0] = bytes32(NOTARY_ROOT ^ 1);
    _assertRejects(_inputs);
  }

  /// @dev A rejection is either `false` or a revert (SumcheckFailed etc.) - both are correct.
  function _assertRejects(bytes32[] memory _inputs) internal view {
    try verifier.verify(_proof(), _inputs) returns (bool _ok) {
      assertFalse(_ok, 'the verifier accepted public inputs the proof was not made for');
    } catch {
      assertTrue(true);
    }
  }
}
