// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.28;

import {Test} from 'forge-std/Test.sol';
import {RagequitHonkVerifier} from '../../contracts/pool/verifiers/RagequitHonkVerifier.sol';
import {INoirVerifier} from '../../contracts/interfaces/verifiers/INoirVerifier.sol';
import {ProofLib} from '../../contracts/pool/lib/ProofLib.sol';

/*
 * CLOSES THE CORRECTNESS HOLE IN sec. 2.5b.
 *
 * PrivacyPool.ragequit and a Groth16 CommitmentVerifier were both inherited from upstream PP, but
 * NO CIRCUIT SOURCE for it existed anywhere in this repo - so no ragequit proof could be produced
 * at all. That was not a missing feature: ragequit is the ONLY exit for a depositor the ASP
 * declines to admit, since withdrawal requires membership. A rejected depositor could neither
 * withdraw nor reclaim.
 *
 * The circuit is now backend/circuits/ragequit (Noir), keeping the fusion on ONE proving stack
 * instead of adding circom/snarkjs for ~15 lines of constraints. The 4 public signals and their
 * order are unchanged, so ProofLib's accessors read the same slots as before.
 *
 * Fixture: test/fixtures/ragequit.proof, regenerated by codegen-verifiers.sh from the committed
 * ragequit/Prover.toml - the same differential-tested vector pp/src/commitment.nr uses
 * (value 10, label 20, nullifier 30, secret 40), cross-checked against poseidon-solidity.
 */
contract RagequitHonkVerifierTest is Test {
  using ProofLib for ProofLib.RagequitProof;

  INoirVerifier internal verifier;

  uint256 internal constant COMMITMENT =
    10718981984499290237711722178490140094119483277114902091282087901089143679380;
  uint256 internal constant NULLIFIER_HASH =
    7532086780038402662674345296860422071861903663404908958571451852914592667893;
  uint256 internal constant VALUE = 10;
  uint256 internal constant LABEL = 20;

  function setUp() public {
    verifier = INoirVerifier(address(new RagequitHonkVerifier()));
  }

  function _proof() internal view returns (ProofLib.RagequitProof memory _p) {
    _p.proof = vm.readFileBinary('test/fixtures/ragequit.proof');
    _p.pubSignals = [COMMITMENT, NULLIFIER_HASH, VALUE, LABEL];
  }

  /// @notice The escape hatch can now actually be proven - it could not be before.
  function test_VerifiesRealRagequitProof() public view {
    ProofLib.RagequitProof memory _p = _proof();
    assertTrue(verifier.verify(_p.proof, _p.ragequitPublicInputsBytes32()));
  }

  /// @notice ProofLib's accessors must read the slots the circuit actually binds.
  function test_AccessorsMatchSlotOrder() public pure {
    ProofLib.RagequitProof memory _p;
    _p.pubSignals = [COMMITMENT, NULLIFIER_HASH, VALUE, LABEL];
    assertEq(_p.commitmentHash(), COMMITMENT);
    assertEq(_p.nullifierHash(), NULLIFIER_HASH);
    assertEq(_p.value(), VALUE);
    assertEq(_p.label(), LABEL);
  }

  /*
   * THE THEFT CASE. PrivacyPool pays out pubSignals[2] directly, so a prover who could inflate
   * `value` while keeping a valid commitment would drain the pool. The circuit binds value INTO
   * the commitment hash, which is what stops it.
   */
  function test_RejectsInflatedValue() public {
    ProofLib.RagequitProof memory _p = _proof();
    _p.pubSignals[2] = VALUE + 1;
    _assertRejects(_p);
  }

  /*
   * THE DOUBLE-SPEND CASE. The contract spends pubSignals[1]. If the nullifier hash were not
   * bound, one note could be reclaimed repeatedly under different nullifiers.
   */
  function test_RejectsTamperedNullifierHash() public {
    ProofLib.RagequitProof memory _p = _proof();
    _p.pubSignals[1] = NULLIFIER_HASH ^ 1;
    _assertRejects(_p);
  }

  function test_RejectsTamperedCommitment() public {
    ProofLib.RagequitProof memory _p = _proof();
    _p.pubSignals[0] = COMMITMENT ^ 1;
    _assertRejects(_p);
  }

  function test_RejectsTamperedLabel() public {
    ProofLib.RagequitProof memory _p = _proof();
    _p.pubSignals[3] = LABEL + 1;
    _assertRejects(_p);
  }

  function _assertRejects(ProofLib.RagequitProof memory _p) internal view {
    try verifier.verify(_p.proof, _p.ragequitPublicInputsBytes32()) returns (bool _ok) {
      assertFalse(_ok);
    } catch {
      assertTrue(true);
    }
  }
}
