// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.28;

import {Test} from 'forge-std/Test.sol';

import {PECDSASHA1Dispatcher} from '../../contracts/passport/dispatchers/PECDSASHA1Dispatcher.sol';
import {PRSASHADispatcher} from '../../contracts/passport/dispatchers/PRSASHADispatcher.sol';
import {PNOAADispatcher} from '../../contracts/passport/dispatchers/PNOAADispatcher.sol';
import {PECDSASHA1Authenticator} from '../../contracts/passport/authenticators/PECDSASHA1Authenticator.sol';

/*
 * The passport dispatchers (sec. 2.18ag).
 *
 * UNREACHABLE TODAY, tested anyway, for the reason sec. 2.18y gives: Active Authentication needs
 * DG15 and our `register_identity` variant is built with `DG15_LEN = 0`, so "unreachable" is a
 * property of one generic in one circuit rather than of this code. A TD3 profile makes all of it
 * live without anyone reopening these files.
 *
 * The ECDSA dispatcher's real vector is the same brainpoolP256r1 signature the authenticator suite
 * uses - generated by openssl over SHA-1 of the challenge and verified by openssl first.
 */
contract PassportDispatchersTest is Test {
    PECDSASHA1Dispatcher internal ecdsa;
    PRSASHADispatcher internal rsa;
    PNOAADispatcher internal noAa;

    bytes internal constant CHALLENGE = hex'aabbccddeeff0011';

    uint256 internal constant X = 0xa0b3b4af8026961e1e8fa6d7e43218513d036bfb49937b7a9484219a2b8ff048;
    uint256 internal constant Y = 0x879de0cef50a489ca54d792b4640e31d59c487099e01459652bee8bef26820fc;
    uint256 internal constant R = 0x69a49bf89e191030202c7780423b1fc091e80c7a68be1a0c730514675aee123d;
    uint256 internal constant S = 0x861ab9baabd2b84be3f38f0cf73ee1f7e202ffbc8265b748439192bbaebafc89;

    function setUp() public {
        ecdsa = new PECDSASHA1Dispatcher();
        ecdsa.__PECDSASHA1Dispatcher_init(address(new PECDSASHA1Authenticator()));

        rsa = new PRSASHADispatcher();
        rsa.__PRSASHADispatcher_init(address(0xBEEF));

        noAa = new PNOAADispatcher();
        noAa.__PNOAADispatcher_init();
    }

    // ── PECDSASHA1Dispatcher ───────────────────────────────────────────────────────────────────

    /// The dispatcher must unpack r/s/x/y and reach the same verdict as the authenticator directly.
    function test_ecdsa_AuthenticatesAGenuineResponse() public view {
        assertTrue(
            ecdsa.authenticate(CHALLENGE, abi.encodePacked(R, S), abi.encodePacked(X, Y)),
            'the dispatcher rejected a response the authenticator accepts'
        );
    }

    function test_ecdsa_RejectsATamperedResponse() public view {
        assertFalse(
            ecdsa.authenticate(CHALLENGE, abi.encodePacked(R ^ 1, S), abi.encodePacked(X, Y)),
            'a tampered response authenticated'
        );
    }

    /*
     * THE BOUNDS - AND THESE TWO TESTS DO NOT PROVE THEM, WHICH IS WORTH SAYING OUT LOUD.
     *
     * Before the fix these four `mload`s took fixed offsets into caller-supplied arrays without
     * consulting their lengths, so a short signature or key pulled ADJACENT MEMORY into r/s/x/y -
     * the shape of sec. 2.18m.
     *
     * BUT REMOVING THE GUARD DOES NOT MAKE THESE FAIL. Whatever the out-of-bounds read picks up
     * still has to satisfy ECDSA verification, and garbage does not, so `authenticate` returns
     * false either way. **They pass with the guard and without it** - the precise vacuity this
     * project keeps finding elsewhere, written here by accident and left documented rather than
     * dressed up (sec. 2.18ag).
     *
     * What they DO pin is that the refusal is explicit and independent of surrounding memory. What
     * would genuinely prove the guard is a case where the adjacent bytes form a VERIFYING tuple,
     * which requires controlling Solidity's memory layout precisely enough to place one - not
     * constructible here, and the reason the guard is defence in depth rather than a fix for a
     * demonstrated exploit.
     */
    function test_ecdsa_RefusesAShortSignature() public view {
        assertFalse(ecdsa.authenticate(CHALLENGE, hex'1234', abi.encodePacked(X, Y)), 'short sig read');
        assertFalse(ecdsa.authenticate(CHALLENGE, '', abi.encodePacked(X, Y)), 'empty sig read');
    }

    function test_ecdsa_RefusesAShortPublicKey() public view {
        assertFalse(ecdsa.authenticate(CHALLENGE, abi.encodePacked(R, S), hex'1234'), 'short key read');
        assertFalse(ecdsa.authenticate(CHALLENGE, abi.encodePacked(R, S), ''), 'empty key read');
    }

    /// The challenge is the last 8 bytes of the identity key, big-endian - it binds the response to
    /// one identity, so getting the order wrong would let a response be replayed under another.
    function test_ecdsa_ChallengeIsTheLastEightBytesBigEndian() public view {
        bytes memory c_ = ecdsa.getPassportChallenge(0x1122334455667788AABBCCDDEEFF0011);

        assertEq(c_.length, 8);
        assertEq(c_, hex'AABBCCDDEEFF0011');
    }

    // ── PRSASHADispatcher ──────────────────────────────────────────────────────────────────────

    function test_rsa_ChallengeMatchesTheEcdsaConvention() public view {
        uint256 key_ = 0x1122334455667788AABBCCDDEEFF0011;
        assertEq(rsa.getPassportChallenge(key_), ecdsa.getPassportChallenge(key_), 'conventions differ');
    }

    // ── PNOAADispatcher ────────────────────────────────────────────────────────────────────────

    /*
     * A passport with no Active Authentication must present NO signature. Returning true regardless
     * would let a document that DOES support AA skip it by claiming not to - so the empty check is
     * the whole security of this dispatcher.
     */
    function test_noAa_AcceptsOnlyAnEmptySignature() public view {
        assertTrue(noAa.authenticate('', '', ''), 'a passport with no AA and no signature was refused');
        assertFalse(noAa.authenticate('', hex'01', ''), 'a signature was accepted on the no-AA path');
    }

    function test_noAa_OmitsTheChallenge() public view {
        assertEq(noAa.getPassportChallenge(12345).length, 0, 'no-AA passports must omit the challenge');
    }
}
