// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.28;

/**
 * @notice Recomputes the recursion tree's root from calldata, so the contract can check that a
 *         batched proof covers EXACTLY the withdrawals it was handed (TODO.md sec. 2.4 / 2.18el).
 *
 * @dev THIS MUST STAY BYTE-IDENTICAL TO THE COMMITMENT THE RECURSION-TREE LEAF BUILDS, generated by
 *      `backend/circuits/build-recursion-tree.py` (the `LEAF_SRC` template). It used to name
 *      `aggregate_withdrawals::batch_commitment`; that circuit was DELETED in `aa50335` when the flat
 *      aggregator was retired, so the counterpart is now the leaf, not the aggregator.
 *      ⚠️ The invariant is unchanged and still load-bearing: the root verifier exposes ONE public
 *      input - this commitment - because it has little EIP-170 margin and N x 7 signals would not
 *      fit. So this function is the ONLY thing tying that single field back to the individual
 *      withdrawals; if it diverges from the circuit, every batch fails to verify.
 *
 *      IT HAD DIVERGED, AND THE GUARD THAT EXISTS TO CATCH THAT COULD NOT FIRE (2026-08-04). This
 *      library folded with chained Poseidon v1 while the circuit had moved to a single keccak256
 *      over the concatenated signals - `aggregate_withdrawals` does not depend on poseidon at all,
 *      and the `fold_signals` this file claimed to mirror no longer exists. Nothing failed, because
 *      `BatchCommitmentTest` compared Solidity against a FROZEN CONSTANT rather than against the
 *      circuit: a pinned number tests that Solidity has not changed, which is not the question. The
 *      test now derives its expectation from the circuit's construction, so moving either side
 *      breaks it.
 *
 *      WHICH SIDE MOVED, established before changing anything: the circuit. It carries no poseidon
 *      dependency, and its own comment describes the contract taking
 *      `uint256(keccak256(...)) % SNARK_SCALAR_FIELD` - the design intended keccak on both sides and
 *      only this file was left behind. Keccak is also far cheaper here: one hash for the whole batch
 *      against two Poseidon permutations per withdrawal.
 *
 *      THE REDUCTION IS PART OF THE COMMITMENT, not a detail. keccak256 gives 256 bits and the field
 *      is ~254, so the circuit folds the digest bytes with Field arithmetic - which IS mod p - and
 *      the contract must reduce explicitly to land on the same element. Omitting `% FIELD_MODULUS`
 *      would agree for most inputs and disagree for the roughly one in 2^-2 that exceed p.
 */
library BatchCommitmentLib {
    /// @notice Public signals per withdrawal - `ProofLib.WithdrawProof.pubSignals` is `uint256[8]`.
    uint256 internal constant PUB_LEN = 7;

    /// @notice BN254's scalar field order, the modulus every public input lives in.
    uint256 internal constant FIELD_MODULUS =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @notice A tree settles exactly two withdrawals per leaf.
    uint256 internal constant PER_LEAF = 2;

    /// @notice The batch does not have a power-of-two size, so no tree could have proved it.
    error NotAPowerOfTwo(uint256 given);
    /// @notice A batch must carry at least one leaf's worth.
    error BatchTooSmall(uint256 given);

    /**
     * @notice The recursion tree's root commitment over `signals`.
     * @dev Mirrors `build-recursion-tree.py`'s two templates EXACTLY, and they are different shapes:
     *
     *      leaf  = keccak(left's 7 signals ++ right's 7 signals)   -- 14 words, 448 bytes
     *      node  = keccak(left commitment ++ right commitment)     --  2 words,  64 bytes
     *      root  = the single public input the generated verifier exposes
     *
     *      WHY NOT ONE FLAT HASH ANY MORE. The flat form matched `aggregate_withdrawals`, which
     *      hashed all N x 7 signals in one go. The tree cannot: each node only ever sees its own two
     *      children, so the commitment is necessarily built bottom-up. A contract still folding flat
     *      recomputes a number the tree never produced, and every batch fails to verify.
     *
     *      ORDER- AND LENGTH-BINDING SURVIVE, structurally. Position is part of every preimage at
     *      every level, so a permutation changes the root; and a batch of a different SIZE is a
     *      different tree DEPTH, which is a different verifier entirely - see `TreeRoot16` vs
     *      `TreeRoot32`, which refuse each other's proofs.
     *
     *      THE REDUCTION IS PART OF THE COMMITMENT at every level, not just the last. keccak gives
     *      256 bits and the field is ~254; the circuit folds digest bytes with Field arithmetic,
     *      which IS mod p, so every intermediate must be reduced here too. Reducing only the root
     *      would agree for most inputs and disagree for the ~1 in 4 intermediates that exceed p.
     */
    function treeCommitment(uint256[PUB_LEN][] memory signals) internal pure returns (uint256) {
        uint256 n = signals.length;
        if (n < PER_LEAF) revert BatchTooSmall(n);
        if (n & (n - 1) != 0) revert NotAPowerOfTwo(n);

        // Level 1: one commitment per PAIR of withdrawals.
        uint256[] memory level = new uint256[](n / PER_LEAF);
        for (uint256 i = 0; i < level.length; ++i) {
            uint256[] memory leaf = new uint256[](PER_LEAF * PUB_LEN);
            for (uint256 j = 0; j < PUB_LEN; ++j) {
                leaf[j] = signals[PER_LEAF * i][j];
                leaf[PUB_LEN + j] = signals[PER_LEAF * i + 1][j];
            }
            level[i] = uint256(keccak256(abi.encodePacked(leaf))) % FIELD_MODULUS;
        }

        // Every level above: pairs of commitments, until one remains.
        while (level.length > 1) {
            uint256[] memory next = new uint256[](level.length / 2);
            for (uint256 i = 0; i < next.length; ++i) {
                next[i] =
                    uint256(keccak256(abi.encodePacked(level[2 * i], level[2 * i + 1]))) % FIELD_MODULUS;
            }
            level = next;
        }
        return level[0];
    }
}
