#!/usr/bin/env python3
"""Emit the wallet's passport-profile table from `passport-profiles.json`.

WHY GENERATED RATHER THAN HAND-WRITTEN. The wallet cannot read `backend/circuits/` at runtime, so the
table has to be bundled - and a bundled COPY of a source of truth is the exact shape that goes stale.
This session already paid for that lesson twice: the consistency checker held a hand-written mirror of
the circuit's AA curve widths and went on reporting a curve as wrong after it was fixed, and
`Registration2.sol`'s header claimed 79 verifiers when there were 88.

So the table is generated, and `profile.test.ts` re-derives every zkType with keccak rather than
trusting the emitted value - a copy that is checked is a cache; one that is not is a rumour.

Run: python3 tools/generate-wallet-profiles.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "backend/circuits/passport-profiles.json"
OUT = ROOT / "frontend/identity-wallet/src/passport/profiles.generated.ts"

# The 14 generics, in the order `register_identity` declares them. Order is part of the contract:
# the selector compares tuples positionally.
FIELDS = [
    "DG1_LEN", "DG15_LEN", "EC_LEN", "SA_LEN", "N", "EC_FIELD_SIZE", "DG_HASH_ALGO",
    "HASH_ALGO", "SIG_TYPE", "DG1_SHIFT", "DG15_SHIFT", "EC_SHIFT", "AA_SIG_TYPE", "AA_SHIFT",
]


def main() -> None:
    m = json.loads(MANIFEST.read_text())
    profiles = m["profiles"]

    rows = []
    for name in sorted(profiles):
        g = profiles[name]["generics"]
        zk = profiles[name].get("zk_type")
        if not zk:
            raise SystemExit(f"{name} has no zk_type - run the consistency checker first")
        tuple_ = ", ".join(str(g[f]) for f in FIELDS)
        rows.append(f'  {{ name: "{name}", zkType: "{zk}", generics: [{tuple_}] }},')

    body = "\n".join(rows)
    OUT.write_text(f'''// GENERATED by tools/generate-wallet-profiles.py - do not edit.
//
// Source of truth: backend/circuits/passport-profiles.json. Regenerate after adding, retiring or
// re-deriving a profile; `profile.test.ts` fails if a zkType here disagrees with keccak of its label,
// so a stale copy is caught rather than trusted.
//
// `generics` is positional, in `register_identity`'s declaration order:
//   [{", ".join(FIELDS)}]

export type PassportProfile = {{
  readonly name: string;
  /** keccak256("Z_NOIR_PASSPORT_" + name) - the key Registration2.passportVerifiers is indexed by. */
  readonly zkType: string;
  readonly generics: readonly number[];
}};

export const PROFILE_FIELDS = [
{chr(10).join(f'  "{f}",' for f in FIELDS)}
] as const;

export const PROFILES: readonly PassportProfile[] = [
{body}
];
''')
    print(f"wrote {OUT.relative_to(ROOT)} with {len(rows)} profiles")


if __name__ == "__main__":
    main()
