#!/usr/bin/env bash
# Generate the UltraHonk verifiers for `register_identity_light`, one per (document type, DG hash).
#
#   ./codegen-light-verifiers.sh              # all ten
#   ./codegen-light-verifiers.sh 93_32 95_20  # specific combinations
#
# WHY THIS EXISTS. The light path had THREE proving systems in the tree at once (sec. 2.18dg):
#   contracts/passport/verifiers2/light/     5 x Groth16     TD3, hashes 160/224/256/384/512
#   contracts/passport/verifiers2/ligh-id/   5 x UltraPlonk  TD1, same five hashes
#   contracts/passport/verifiers/            1 x UltraHonk   TD1, SHA-256 ONLY
# so exactly one of the ten had a Honk equivalent, and the other nine kept a dying backend alive.
#
# There is no per-profile mystery here, unlike the passport circuits: `register_identity_light` is
# generic over exactly TWO parameters and reads only `dg1` and `sk_identity`. Everything the ten
# variants need is (DG1_LEN, DG_HASH_ALGO), both known - so the whole family is a template loop, and
# the circuits are tiny (2^16) rather than the 2^18..2^25 of the full passport circuits.
set -euo pipefail

CIRCUITS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${CIRCUITS_DIR}/../contracts/contracts/passport/verifiers"
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

# DG1_LEN is the MRZ length and IS the document type: 93 = TD3 passport, 95 = TD1 identity card.
# DG_HASH_ALGO is the digest size in BYTES; the verifier names use bits, matching the families above.
ALL=(93_20 93_28 93_32 93_48 93_64 95_20 95_28 95_32 95_48 95_64)
if [ "$#" -gt 0 ]; then COMBOS=("$@"); else COMBOS=("${ALL[@]}"); fi

command -v nargo >/dev/null || { echo "nargo is not on PATH" >&2; exit 1; }
command -v bb >/dev/null || { echo "bb is not on PATH (try: export PATH=\$PATH:~/.bb)" >&2; exit 1; }

mkdir -p "${WORK}/src"
cat > "${WORK}/Nargo.toml" <<EOF
[package]
name = "register_identity_light_gen"
type = "bin"
authors = [""]

[dependencies]
noir_dl = {path = "${CIRCUITS_DIR}/noir_dl_lib"}
EOF

built=0; failed=()
for combo in "${COMBOS[@]}"; do
  dg1="${combo%_*}"; hash_bytes="${combo#*_}"
  bits=$(( hash_bytes * 8 ))
  # TD1 keeps the existing `LightID` name, TD3 the existing `Light` name, so each new verifier is
  # visibly the replacement for one specific old file rather than a parallel naming scheme.
  if [ "${dg1}" = "95" ]; then name="RegisterIdentityLightID${bits}HonkVerifier"; else name="RegisterIdentityLight${bits}HonkVerifier"; fi
  echo "=== ${name}  (DG1_LEN=${dg1}, DG_HASH_ALGO=${hash_bytes})"

  cat > "${WORK}/src/main.nr" <<EOF
// GENERATED by codegen-light-verifiers.sh - do not edit.
// register_identity_light<DG1_LEN=${dg1}, DG_HASH_ALGO=${hash_bytes}>
use noir_dl::lite::register_identity_light;

fn main(dg1: [u8; ${dg1}], sk_identity: Field) -> pub (Field, Field, Field) {
	let tmp = register_identity_light::<${dg1}, ${hash_bytes}>(dg1, sk_identity);
	(tmp.0, tmp.1, tmp.2)
}
EOF

  if ! ( cd "${WORK}" && nargo compile >/dev/null ); then
    echo "!! FAILED_COMPILE ${name}" >&2; failed+=("${name}"); continue
  fi
  artifact="target/register_identity_light_gen.json"
  if ! ( cd "${WORK}" && bb write_vk -t evm -b "${artifact}" -o target >/dev/null 2>&1 ); then
    echo "!! FAILED_VK ${name}" >&2; failed+=("${name}"); continue
  fi
  ( cd "${WORK}" && bb write_solidity_verifier -t evm -k target/vk -o "${OUT_DIR}/${name}.sol" >/dev/null 2>&1 )
  # bb names the contract after the artifact, so rename it to the file it lives in.
  # RENAME THE CONCRETE CONTRACT ONLY. bb emits `abstract contract BaseZKHonkVerifier` first and
  # `contract HonkVerifier is BaseZKHonkVerifier(...)` last; a regex for `\w*HonkVerifier` matches the
  # BASE first and renames the wrong one, leaving the child inheriting a name that no longer exists.
  python3 - "${OUT_DIR}/${name}.sol" "${name}" <<'PY'
import re,sys
p,name=sys.argv[1],sys.argv[2]
s=open(p).read()
s2,n=re.subn(r'^contract HonkVerifier is\b', f'contract {name} is', s, count=1, flags=re.M)
if n!=1:
    sys.exit(f"expected exactly one 'contract HonkVerifier is' in {p}, found {n}")
if 'abstract contract BaseZKHonkVerifier is' not in s2:
    sys.exit(f"{p}: base contract lost its name - refusing to write")
open(p,'w').write(s2)
PY
  built=$((built+1))
done

echo
echo "generated ${built} light verifier(s) into ${OUT_DIR}"
[ "${#failed[@]}" -gt 0 ] && { echo "FAILED: ${failed[*]}" >&2; exit 1; }
exit 0
